ALTER TABLE PENGGUNA ALTER PASSWORD varchar(255) NOT NULL;
ALTER TABLE PENGGUNA ADD VEKTOR_PROFIL LONG VARCHAR NULL;
ALTER TABLE PENGGUNA ADD IS_ONBOARDED smallint DEFAULT 0 NOT NULL;
ALTER TABLE DESTINASI_WISATA ADD VEKTOR_ITEM LONG VARCHAR NULL;
ALTER TABLE HISTORY_REKOMENDASI ADD TIPE_INTERAKSI varchar(20) NULL;
ALTER TABLE HISTORY_REKOMENDASI ADD IS_INTERACTED smallint DEFAULT 0 NOT NULL;
CREATE INDEX MEMILIKI2_FK ON PREFERENSI_AWAL (ID_PENGGUNA ASC);
